### ISSUE TITLE
Request a package

### ISSUE THREAD

**Issue by PoloNX** [zeromake/xrepo#7]
Hello ! I saw you made a `xmake.lua` on [borealis](https://github.com/xfangfang/borealis) do you think it's possible to make a borealis package ? I created a [toolchain ](https://github.com/PoloNX/xmake-devkitpro) with xmake and I wanted to create a borealis package. I wanted to use your `xmake.lua` but I didn't success. There's some errors because I'm not using the good plat.

**Comment by PoloNX** [comment]
For example with the following code :

```lua
package("borealis")
    set_homepage("https://github.com/PoloNX/borealis")
    set_description("Hardware accelerated, Nintendo Switch inspired UI library for PC, Android, iOS, PSV, PS4 and Nintendo Switch")
    set_license("Apache-2.0")

    add_urls("https://github.com/PoloNX/borealis.git")
    add_versions("2024.04.18", "ae9b053ce527faaef5356d1acfd4f7a392604451")

    on_install(function (package)
        import("package.tools.xmake").install(package)
    end)

    on_test(function (package)
        assert(package:has_cfuncs("brls::Application::init", {includes = "borealis.hpp"}))
    end)

```

I'm getting an include error :


``error: @programdir\core\sandbox\modules\os.lua:132: cannot link gl.h to glad.h, Unknown Error (1314)``

**Comment by zeromake** [comment]
@PoloNX 
borealis pkg on wiliwili
https://github.com/xfangfang/wiliwili/blob/yoga/xmake.lua#L38

**Comment by PoloNX** [comment]
Thanks will try to use it

**Comment by PoloNX** [comment]
Tried with the test.lua 
``xmake l scripts/test.lua -vD --shallow borealis``

And I still have this error 

``error: @programdir\core\sandbox\modules\os.lua:132: cannot link gl.h to glad.h, Unknown Error (1314)``

here is a full log

[log.txt](https://github.com/zeromake/xrepo/files/15052058/log.txt)

**Comment by zeromake** [comment]
@PoloNX 
https://github.com/zeromake/xrepo/blob/master/packages/b/borealis/xmake.lua

**Comment by PoloNX** [comment]
Thanks @zeromake for your hard work ! all issues seems to be fixed except at the end when I have one compilation error with the file ``glfw_video.cpp``

```
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared\minwindef.h(130): warning C4005: 'APIENTRY': macro redefinition
C:\Users\geyre\AppData\Local\.xmake\packages\x\xfangfang_glfw\2024.02.26-alpha\3b6dc0458a404eb685229d88af670da4\include\GLFW/glfw3.h(123): note: see previous definition of 'APIENTRY'
library\lib\platforms\glfw\glfw_video.cpp(313): error C2589: '(': token following '::' is not legal
library\lib\platforms\glfw\glfw_video.cpp(313): error C2062: unexpected type 'unknown-type'
library\lib\platforms\glfw\glfw_video.cpp(313): error C2059: syntax error: ')'
```

**Comment by zeromake** [comment]
@PoloNX 
should be windows define var, I add to xrepo use osx pc test, I'll take a look at it at night

**Comment by PoloNX** [comment]
Thanks, I will try on my arch linux

**Comment by PoloNX** [comment]
It's an issue with windows.h. you have to add two defines in the file port/xmake.lau like this
```
    if is_plat("window") then
        add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN")
    end
```

**Comment by PoloNX** [comment]
Now I have one error when I'm building example. it's about glad 

```
error: @programdir\core\main.lua:329: @programdir\actions\build\main.lua:148: @programdir\modules\async\runjobs.lua:322: @programdir\actions\build\kinds\binary.lua:53: @programdir\modules\core\tools\link.lua:175: borealis.lib(glfw_video.cpp.obj) : error LNK2019: unresolved external symbol gladLoadGLLoader referenced in function "public: __cdecl brls::GLFWVideoContext::GLFWVideoContext(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned int,unsigned int,float,float)" (??0GLFWVideoContext@brls@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@IIMM@Z)
build\windows\x64\release\demo.exe : fatal error LNK1120: 1 unresolved externals
```

**Comment by zeromake** [comment]
@PoloNX glad 2.x version gladLoadGLLoader change,but borealis not support glad 2.x, only glad 0.1.x

**Comment by zeromake** [comment]
@PoloNX 
added glad 0.1.36 on xrepo support to borealis

**Comment by PoloNX** [comment]
Fixed it. thanks for your huge works. I'll made a pr to add switch support
